version: "3.9"

services:

  zookeeper:
    image: fl0r3k/zookeeper:3.6.3

  kafka:
    image: fl0r3k/kafka:3.0.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: REPLICATION
      KAFKA_LISTENERS: CLIENTS://0.0.0.0:9092,REPLICATION://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: CLIENTS://localhost:9092,REPLICATION://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CLIENTS:PLAINTEXT,REPLICATION:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
